package se.kth.ki.waitapp.init.seed;

import java.util.List;

import org.hibernate.reactive.mutiny.Mutiny;

import jakarta.enterprise.context.ApplicationScoped;
import jakarta.inject.Inject;
import se.kth.ki.waitapp.core.interfaces.repository.ITaskRepository;
import se.kth.ki.waitapp.core.model.sprint.Level;
import se.kth.ki.waitapp.core.model.sprint.SprintType;
import se.kth.ki.waitapp.core.model.sprint.Task;
import se.kth.ki.waitapp.core.model.sprint.TaskVariant;

@ApplicationScoped
public class TaskSeeder extends GenericSeeder<Task> {

        @Inject
        public TaskSeeder(ITaskRepository repository, Mutiny.SessionFactory sf) {
                super(repository, sf, List.of(

                                // Walking, Cycling, Swimming Task (Physical type)
                                Task.builder()
                                                .type(SprintType.PHYSICAL)
                                                .level(Level.NORMAL)
                                                .variant(TaskVariant.ACTIVE)
                                                .title("walking-cycling-swimming-30min-workout")
                                                .description("walking-cycling-swimming-30min-workout-desc")
                                                .videoURL("")
                                                .build()

                                , Task.builder()
                                                .type(SprintType.PHYSICAL)
                                                .level(Level.NORMAL)
                                                .variant(TaskVariant.ACTIVE)
                                                .title("walking-cycling-swimming-45min-workout")
                                                .description("walking-cycling-swimming-45min-workout-desc")
                                                .videoURL("")
                                                .build()

                                , Task.builder()
                                                .type(SprintType.PHYSICAL)
                                                .level(Level.INTENSE)
                                                .variant(TaskVariant.ACTIVE)
                                                .title("walking-cycling-swimming-60min-workout")
                                                .description("walking-cycling-swimming-60min-workout-desc")
                                                .videoURL("")
                                                .build()

                                // Resting Task (REST variant)
                                , Task.builder()
                                                .type(SprintType.PHYSICAL)
                                                .level(Level.NORMAL)
                                                .variant(TaskVariant.REST)
                                                .title("resting-workout")
                                                .description("resting-workout-desc")
                                                .videoURL("")
                                                .build()

                                , Task.builder()
                                                .type(SprintType.PHYSICAL)
                                                .level(Level.NORMAL)
                                                .variant(TaskVariant.REST)
                                                .title("resting-workout-medium")
                                                .description("resting-workout-medium-desc")
                                                .videoURL("")
                                                .build()

                                , Task.builder()
                                                .type(SprintType.PHYSICAL)
                                                .level(Level.INTENSE)
                                                .variant(TaskVariant.REST)
                                                .title("resting-workout-high")
                                                .description("resting-workout-high-desc")
                                                .videoURL("")
                                                .build()

                                // Exercise 3 Tasks (Physical type)
                                , Task.builder()
                                                .type(SprintType.PHYSICAL)
                                                .level(Level.NORMAL)
                                                .variant(TaskVariant.ACTIVE)
                                                .title("exercise-1")
                                                .description("simple-three-workouts-desc")
                                                .videoURL("https://www.youtube.com/embed/-1qQjeHZEfY")
                                                .build()

                                , Task.builder()
                                                .type(SprintType.PHYSICAL)
                                                .level(Level.NORMAL)
                                                .variant(TaskVariant.ACTIVE)
                                                .title("exercise-1-medium")
                                                .description("simple-three-workouts-medium-desc")
                                                .videoURL("https://www.youtube.com/embed/-1qQjeHZEfY")
                                                .build()

                                , Task.builder()
                                                .type(SprintType.PHYSICAL)
                                                .level(Level.INTENSE)
                                                .variant(TaskVariant.ACTIVE)
                                                .title("exercise-1-high")
                                                .description("simple-three-workouts-high-desc")
                                                .videoURL("https://www.youtube.com/embed/-1qQjeHZEfY")
                                                .build()

                                , Task.builder()
                                                .type(SprintType.PHYSICAL)
                                                .level(Level.NORMAL)
                                                .variant(TaskVariant.ACTIVE)
                                                .title("exercise-2")
                                                .description("simple-three-workouts-desc")
                                                .videoURL("https://www.youtube.com/embed/qW3Zr1VAJYE")
                                                .build()

                                , Task.builder()
                                                .type(SprintType.PHYSICAL)
                                                .level(Level.NORMAL)
                                                .variant(TaskVariant.ACTIVE)
                                                .title("exercise-2-medium")
                                                .description("simple-three-workouts-medium-desc")
                                                .videoURL("https://www.youtube.com/embed/qW3Zr1VAJYE")
                                                .build()

                                , Task.builder()
                                                .type(SprintType.PHYSICAL)
                                                .level(Level.INTENSE)
                                                .variant(TaskVariant.ACTIVE)
                                                .title("exercise-2-high")
                                                .description("simple-three-workouts-high-desc")
                                                .videoURL("https://www.youtube.com/embed/qW3Zr1VAJYE")
                                                .build()

                                , Task.builder()
                                                .type(SprintType.PHYSICAL)
                                                .level(Level.NORMAL)
                                                .variant(TaskVariant.ACTIVE)
                                                .title("exercise-3")
                                                .description("simple-three-workouts-desc")
                                                .videoURL("https://www.youtube.com/embed/179xw7lGbPc")
                                                .build()

                                , Task.builder()
                                                .type(SprintType.PHYSICAL)
                                                .level(Level.NORMAL)
                                                .variant(TaskVariant.ACTIVE)
                                                .title("exercise-3-medium")
                                                .description("simple-three-workouts-medium-desc")
                                                .videoURL("https://www.youtube.com/embed/179xw7lGbPc")
                                                .build()

                                , Task.builder()
                                                .type(SprintType.PHYSICAL)
                                                .level(Level.INTENSE)
                                                .variant(TaskVariant.ACTIVE)
                                                .title("exercise-3-high")
                                                .description("simple-three-workouts-high-desc")
                                                .videoURL("https://www.youtube.com/embed/179xw7lGbPc")
                                                .build()

                                // Exercise 4 Tasks (Physical type)
                                , Task.builder()
                                                .type(SprintType.PHYSICAL)
                                                .level(Level.NORMAL)
                                                .variant(TaskVariant.ACTIVE)
                                                .title("exercise-1")
                                                .description("simple-three-workouts-desc")
                                                .videoURL("https://www.youtube.com/embed/XqBtWqmitk8")
                                                .build()

                                , Task.builder()
                                                .type(SprintType.PHYSICAL)
                                                .level(Level.NORMAL)
                                                .variant(TaskVariant.ACTIVE)
                                                .title("exercise-1-medium")
                                                .description("simple-three-workouts-medium-desc")
                                                .videoURL("https://www.youtube.com/embed/XqBtWqmitk8")
                                                .build()

                                , Task.builder()
                                                .type(SprintType.PHYSICAL)
                                                .level(Level.INTENSE)
                                                .variant(TaskVariant.ACTIVE)
                                                .title("exercise-1-high")
                                                .description("simple-three-workouts-high-desc")
                                                .videoURL("https://www.youtube.com/embed/XqBtWqmitk8")
                                                .build()

                                , Task.builder()
                                                .type(SprintType.PHYSICAL)
                                                .level(Level.NORMAL)
                                                .variant(TaskVariant.ACTIVE)
                                                .title("exercise-2")
                                                .description("simple-three-workouts-desc")
                                                .videoURL("https://www.youtube.com/embed/Ypxw7Jcit1c")
                                                .build()

                                , Task.builder()
                                                .type(SprintType.PHYSICAL)
                                                .level(Level.NORMAL)
                                                .variant(TaskVariant.ACTIVE)
                                                .title("exercise-2-medium")
                                                .description("simple-three-workouts-medium-desc")
                                                .videoURL("https://www.youtube.com/embed/Ypxw7Jcit1c")
                                                .build()

                                , Task.builder()
                                                .type(SprintType.PHYSICAL)
                                                .level(Level.INTENSE)
                                                .variant(TaskVariant.ACTIVE)
                                                .title("exercise-2-high")
                                                .description("simple-three-workouts-high-desc")
                                                .videoURL("https://www.youtube.com/embed/Ypxw7Jcit1c")
                                                .build()

                                , Task.builder()
                                                .type(SprintType.PHYSICAL)
                                                .level(Level.NORMAL)
                                                .variant(TaskVariant.ACTIVE)
                                                .title("exercise-3")
                                                .description("simple-three-workouts-desc")
                                                .videoURL("https://www.youtube.com/embed/USyW4xv3BIQ")
                                                .build()

                                , Task.builder()
                                                .type(SprintType.PHYSICAL)
                                                .level(Level.NORMAL)
                                                .variant(TaskVariant.ACTIVE)
                                                .title("exercise-3-medium")
                                                .description("simple-three-workouts-medium-desc")
                                                .videoURL("https://www.youtube.com/embed/USyW4xv3BIQ")
                                                .build()

                                , Task.builder()
                                                .type(SprintType.PHYSICAL)
                                                .level(Level.INTENSE)
                                                .variant(TaskVariant.ACTIVE)
                                                .title("exercise-3-high")
                                                .description("simple-three-workouts-high-desc")
                                                .videoURL("https://www.youtube.com/embed/USyW4xv3BIQ")
                                                .build()

                                , Task.builder()
                                                .type(SprintType.PHYSICAL)
                                                .level(Level.NORMAL)
                                                .variant(TaskVariant.ACTIVE)
                                                .title("exercise-4")
                                                .description("simple-three-workouts-desc")
                                                .videoURL("https://www.youtube.com/embed/179xw7lGbPc")
                                                .build()

                                , Task.builder()
                                                .type(SprintType.PHYSICAL)
                                                .level(Level.NORMAL)
                                                .variant(TaskVariant.ACTIVE)
                                                .title("exercise-4-medium")
                                                .description("simple-three-workouts-medium-desc")
                                                .videoURL("https://www.youtube.com/embed/179xw7lGbPc")
                                                .build()

                                , Task.builder()
                                                .type(SprintType.PHYSICAL)
                                                .level(Level.INTENSE)
                                                .variant(TaskVariant.ACTIVE)
                                                .title("exercise-4-high")
                                                .description("simple-three-workouts-high-desc")
                                                .videoURL("https://www.youtube.com/embed/179xw7lGbPc")
                                                .build()

                                // Cardio and Strength Task (Physical type)
                                , Task.builder()
                                                .type(SprintType.PHYSICAL)
                                                .level(Level.NORMAL)
                                                .variant(TaskVariant.ACTIVE)
                                                .title("cardio-strength-1")
                                                .description("cardio-and-strength")
                                                .videoURL("")
                                                .build()

                                , Task.builder()
                                                .type(SprintType.PHYSICAL)
                                                .level(Level.NORMAL)
                                                .variant(TaskVariant.ACTIVE)
                                                .title("cardio-strength-2")
                                                .description("cardio-and-strength")
                                                .videoURL("")
                                                .build()

                                , Task.builder()
                                                .type(SprintType.PHYSICAL)
                                                .level(Level.INTENSE)
                                                .variant(TaskVariant.ACTIVE)
                                                .title("cardio-strength-3")
                                                .description("cardio-and-strength")
                                                .videoURL("")
                                                .build()));

        }
}
