services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: waitapp
    volumes:
      - ./db/init/:/docker-entrypoint-initdb.d/
      - dbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    environment:
      KEYCLOAK_ADMIN: admin # change on deployment
      KEYCLOAK_ADMIN_PASSWORD: admin # change on deployment
      KEYCLOAK_USER: admin # change on deployment
      KEYCLOAK_PASSWORD: admin # change on deployment
      KEYCLOAK_IMPORT: /opt/keycloak/data/import/realm-config.json
      JAVA_OPTS: "-Dkeycloak.import=/opt/keycloak/data/import/"
    volumes:
      - keycloak-data:/opt/keycloak/data
      - ./keycloak/realms:/opt/keycloak/data/import
      #- ./keycloak/themes:/opt/keycloak/themes
    ports:
      - "9090:8080"
    command:
      - start-dev
    restart: unless-stopped

volumes:
  dbdata:
  keycloak-data:
